---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  db_host: mysql-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-file
data:
  db.conf: |
    [conf]
    port=1234
    buffer=16MB
