---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        command: ['sh', '-c']
        args:
        - while true; do
            echo "$(date) INFO => some app data" >> /var/log/myapp.log;
            sleep 5;
          done;
        volumeMounts:
        - name: log-data
          mountPath: /var/log
      - name: log-sidecar
        image: busybox
        command: ['sh', '-c']
        args:
        - tail -f /var/log/myapp.log
        volumeMounts:
        - name: log-data
          mountPath: /var/log
      volumes:
      - name: log-data
        emptyDir: {}
