---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kube-system
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-system
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector: # Manually choose which node to schedule on based on a label
        kubernetes.io/hostname: control-plane
      tolerations: # Allow for the pod to be scheduled on a tainted node
      - effect: NoSchedule
        operator: Exists
      affinity:
        podAffinity: # Schedule the pod only on a node that has a pod with 'component: etcd' label i.e., install the pod only on nodes with etcd on them
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - etcd
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity: # Do not schedule the pod on a node that has a pod with 'app: nginx' label i.e., allow for only one NGINX pod per node
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
